#! /usr/bin/env python
"""
ifupdown-ng  -  Next-generation network interface configuration tool
Copyright (C) 2012-2013  Kyle Moffett <kyle@moffetthome.net>

This program is free software; you can redistribute it and/or modify it
under the terms of version 2 of the GNU General Public License, as
published by the Free Software Foundation.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
for more details.

You should have received a copy of the GNU General Public License along
with this program; otherwise you can obtain it here:
  http://www.gnu.org/licenses/gpl-2.0.txt
"""

## Load various commands that will be used.  We don't actually care about any
## objects provided here, just that the classes are loaded and register with
## the main function in ifupdown_ng.commands.
# pylint: disable-msg=W0611
import ifupdown_ng.commands.ifupdown
import ifupdown_ng.commands.ifquery
# pylint: enable-msg=W0611

## Now execute the main function
from ifupdown_ng.commands import main
if __name__ == '__main__':
	main()
